
# Most of the maintainers of this code are professional engineers,
# not professional Rubyists.  The style guide for this project
# has been modified accordingly, with explanations given below.
# Where a Cop is not listed, it uses the Rubocop defaults.

AllCops:
  Exclude:
    - 'measures/**/*'
    - 'openstudio-standards/data/**/*'
    - 'openstudio-standards/test/**/*'
    - 'openstudio-standards/lib/openstudio-standards/hvac_sizing/**/*'
    - 'openstudio-standards/lib/openstudio-standards/btap/**/*'

# ==================== Linters ====================

# Allow variable initialization to indicate
# what variable is going to be set by the next
# block of code.
Lint/UselessAssignment:
  Enabled: false

# Allow unused arguments in anticipation that
# those arguments will be used in the future.
# The ruby _arg convention will not be understood
# by many of the non-Rubyists maintaining the code.
Lint/UnusedMethodArgument:
  Enabled: false  
  
# Allow unused blow arguments.
# The ruby _arg convention will not be understood
# by many of the non-Rubyists maintaining the code.
Lint/UnusedBlockArgument:
  Enabled: false  
  
# ==================== Metrics ====================
Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Max: 48

# Allow long lines to encourage sufficiently
# detailed user-facing log messages.
Metrics/LineLength:
  Max: 1000

# Longer parameter list limits for methods that
# add HVAC systems
Metrics/ParameterLists:
  Max: 15
  
# Disable this metric.  This is a complex engineering-focused library.
Metrics/ClassLength:
  Enabled: false

# Disable this metric.  This is a complex engineering-focused library.  
Metrics/MethodLength:
  Enabled: false
  
# Disable this metric.  This is a complex engineering-focused library.
Metrics/ModuleLength:
  Enabled: false  
  
# Disable this metric.  This is a complex engineering-focused library.
Metrics/AbcSize:
  Enabled: false
  
# Disable this metric.  This is a complex engineering-focused library.
Metrics/PerceivedComplexity:
  Enabled: false

# Disable this metric.  This is a complex engineering-focused library.
Metrics/CyclomaticComplexity:
  Enabled: false
  
# ==================== Styles ====================
  
# WordArray enforces how array literals of word-like strings should be expressed.
# Enforce ['Word1', 'Word2'] for readability
Style/WordArray:
  EnforcedStyle: brackets

# Intentionally allow set_foo because these methods do not
# take have cooresponding getters.
Style/AccessorMethodName:
  Enabled: false

# Allow indented case statements
Style/CaseIndentation:
  Enabled: false

# Disabled because in most of this codebase,
# the current approach is more readable.
Style/GuardClause:
  Enabled: false  

# Allow this type of nesting for logic clarity.
Style/IfInsideElse:
  Enabled: false  
 
# This library encourages explicit returns for clarity
Style/RedundantReturn:
  Enabled: false

# Allow duplication inside conditional branches to keep
# code that does certain tasks more consolidated.
Style/IdenticalConditionalBranches:
  Enabled: false  

# Do not force people to use Next.
Style/Next:
  Enabled: false

# Do not force people to use one-line if statements.
Style/IfUnlessModifier:
  Enabled: false

# Allow global variables because using $os_standards 
# to avoid passing it around to every method.
# Should not use any more global variables though.
Style/GlobalVars:
  Enabled: false 
 
# Ignore file name convention; choices based on OpenStudio C++ class names
Style/FileName:
  Enabled: false

# Documentation will be covered by YARD.
Style/Documentation:
  Enabled: false  
  
# Unclear what this Cop is about; disregard
Style/ClassAndModuleChildren:
  Enabled: false
