AllCops:
  Exclude:
    - 'documentation/**/*'

# ==================== Linters ====================
Lint/AmbiguousOperator:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/UnreachableCode:
  Enabled: false

Lint/UselessAssignment:
  Enabled: true

# ==================== Styles / Metrics ====================
# Offense count: 4
Metrics/BlockNesting:
  Max: 4

# Offense count: 18
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 500

# Offense count: 27
Metrics/CyclomaticComplexity:
  Max: 48

# Offense count: 974
Metrics/LineLength:
  Max: 1200

# Offense count: 87
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 350

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 8

# ==================== Disabled on Purpose ====================
Style/AccessorMethodName:
  Enabled: true

# Need to allow indented case statements
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Do NOT enable.  For some reason this is catchy any next which I feel are okay.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/Next:
  Enabled: false

# Do NOT enable this because it appears $? is different than $CHILD_STATUS.
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: false

# More Changes -- pulled from https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

# Allow redundant returns
Style/RedundantReturn:
  Description: 'Do not use return where it is not required.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-explicit-return'
  Enabled: false

Style/NumericLiterals:
  Description: 'Add underscores to large numeric literals to improve readability.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics'
  Enabled: false

Lint/UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false

Lint/UnusedMethodArgument:
  Description: 'Checks for unused method arguments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#underscore-unused-vars'
  Enabled: false